In [1]:
from sage.all_cmdline import *   # import sage library

# from solid_angle_code.solid_angle_sage import *
from solid_angle_code.solid_angle_sage import solid_angle_general, solid_angle_2d, solid_angle_3d
import time
import numpy as np
import random

SEED = 2
SF = 1

seed = SEED
np.random.seed(SEED)
np.random.seed(seed)
random.seed(seed)
# torch.manual_seed(seed)
# torch.cuda.manual_seed_all(seed)
# torch.manual_seed(seed)
# torch.backends.cudnn.deterministic = True
# torch.backends.cudnn.benchmark = False
# torch.backends.cudnn.enabled = False

sf = SF

In [2]:
result1_20, result1_40, result1_80, result1_160, = list(), list(), list(), list(), 
size_list = [2, 3, 4, 8, 16, 32, 64, 128, 256, 512]
size_list = [4]
cone_list1 = []
for s in size_list:
    print(f"vector dim: {s}, number of vector: {s}")
    start = time.time()
    ray = np.round(np.random.normal(size=[s, s]), sf)*10**sf
    ray = np.asarray(ray, dtype=int)
    cone_list1.append(ray)
    print(f"{ray=}")
    A = matrix(ray)
    start = time.time()
    a = solid_angle_general(A, deg=20)
    print(f" ## solid angle(deg=20): {a}")
    result1_20.append(a)
    solid_angle_time = time.time()
    print(f"Time to measure solid angle : {round(solid_angle_time - start, 2)}")
    start = time.time()
    b = solid_angle_general(A, deg=40)
    print(f" ## solid angle(deg=40): {b}")
    result1_40.append(b)
    solid_angle_time = time.time()
    print(f"Time to measure solid angle : {round(solid_angle_time - start, 2)}")
    start = time.time()
    c = solid_angle_general(A, deg=80)
    print(f" ## solid angle(deg=80): {c}")
    result1_80.append(c)
    solid_angle_time = time.time()
    print(f"Time to measure solid angle : {round(solid_angle_time - start, 2)}")
    d = solid_angle_general(A, deg=160)
    print(f" ## solid angle(deg=160): {d}")
    result1_160.append(d)
    solid_angle_time = time.time()
    print(f"Time to measure solid angle : {round(solid_angle_time - start, 2)}")
    print()



vector dim: 4, number of vector: 4
ray=array([[ -4,  -1, -21,  16],
       [-18,  -8,   5, -12],
       [-11,  -9,   6,  23],
       [  0, -11,   5,  -6]])


 ## solid angle(deg=20): 0.04012700973195804
Time to measure solid angle : 4.34


 ## solid angle(deg=40): 0.04012700973195804
Time to measure solid angle : 4.11


 ## solid angle(deg=80): 0.04012700973195804
Time to measure solid angle : 4.11
 ## solid angle(deg=160): 0.04012700973195804
Time to measure solid angle : 8.19



In [3]:
result2_20, result2_40, result2_80, result2_160, = list(), list(), list(), list(), 
size_list = [2, 3, 4, 8, 16, 32, 64, 128, 256, 512]
# size_list = [8]
cone_list1 = []
for s in size_list:
    print(f"vector dim: {s}, number of vector: {s}")
    start = time.time()
    ray = np.round(np.random.normal(size=[s, s]), sf)*10**sf
    ray = np.asarray(ray, dtype=int)
    cone_list1.append(ray)
    print(f"{ray=}")
    A = matrix(ray)
    start = time.time()
    a = solid_angle_general(A, deg=10)
    print(f" ## solid angle(deg=10): {a}")
    result2_20.append(a)
    solid_angle_time = time.time()
    print(f"Time to measure solid angle : {round(solid_angle_time - start, 2)}")
    # start = time.time()
    # b = solid_angle_general(A, deg=40)
    # print(f" ## solid angle(deg=40): {b}")
    # result2_40.append(b)
    # solid_angle_time = time.time()
    # print(f"Time to measure solid angle : {round(solid_angle_time - start, 2)}")
    # start = time.time()
    # c = solid_angle_general(A, deg=80)
    # print(f" ## solid angle(deg=80): {c}")
    # result2_80.append(bc)
    # solid_angle_time = time.time()
    # print(f"Time to measure solid angle : {round(solid_angle_time - start, 2)}")
    # d = solid_angle_general(A, deg=160)
    # print(f" ## solid angle(deg=160): {d}")
    # result2_160.append(d)
    # solid_angle_time = time.time()
    # print(f"Time to measure solid angle : {round(solid_angle_time - start, 2)}")
    print()



vector dim: 2, number of vector: 2
ray=array([[ 0, 12],
       [-7,  0]])
 ## solid angle(deg=20): 0.25000000000000006
Time to measure solid angle : 0.01

vector dim: 3, number of vector: 3
ray=array([[ -9,  -2,   3],
       [-10,  -3,  -2],
       [ -6, -12, -14]])
 ## solid angle(deg=20): 0.038242452344209435
Time to measure solid angle : 0.04

vector dim: 4, number of vector: 4
ray=array([[ -2,  -3,  22, -24],
       [  1,   4,  14,   5],
       [ -8,   0,   5,  -3],
       [  8, -19,  17,  15]])


 ## solid angle(deg=20): 0.024470409880112853
Time to measure solid angle : 1.21

vector dim: 8, number of vector: 8
ray=array([[ -3,   6,   0,  -8,   1,  10,  -4,  -4],
       [ -1,   4,  13,  -6,   5,   2, -19,  -4],
       [ -1,   0,   3, -20,   0,  -7, -14,   5],
       [  7,  -7,   8,  -4,   1, -11,  16, -27],
       [ -1,   7, -20,  -2,  -1,   8,  12,  -4],
       [-14,  14,  12,  -5,   4,   4,   6,   2],
       [ 14, -17,  10,   4,  -2,  12, -23,  12],
       [  4, -11,   4,  -3,  26,  18,   4,  -7]])


 ## solid angle(deg=20): 0.00030109726356532235
Time to measure solid angle : 226066.6

vector dim: 16, number of vector: 16
ray=array([[ -6,  -3,  -6,  -9,  -6,  -3,  -5,  -7,  -9,  26, -15, -10,   4,
         -3,   4,   8],
       [ 13,   8, -10,  11, -18,  -1,  -5, -11,   6,  -2,  10, -15,   8,
          5,   1, -14],
       [ -3, -15, -21,  33,  10,  18,  -4,   7,   7,   6,   0,  -2, -21,
          6,   4,  11],
       [ -3,  17,  -4, -13,   9,  -5, -13,   1,   8,   2,   5,  41,   8,
         15, -20,   4],
       [  8,  -4,  -9,   4,  -3,  -6,  11,  13,   3,  -5,   5,   8,   6,
        -15,  -3,   4],
       [  6,  10,   8, -11,  -7, -12,  18,   2,   6,  10,  -3, -12,  -4,
         -1,  15,   9],
       [-11,   7,   7, -11,  -1, -19,   3,  -3, -14,  -7,   2,  -6,   3,
          6,  -8,  -3],
       [ 21,   1,  -8,   1, -13,  11,   4,  11,   9,   4,  10,   2,  -7,
        -10,  -4, -25],
       [ 18, -17,  -1, -13, -20,  -1,  -3,  -2,   5,  -6,   4,   5,  -3,
         -3,   5,   1]

 ## solid angle(deg=20): 1.2034325390335816e-34
Time to measure solid angle : 0.82

vector dim: 128, number of vector: 128
ray=array([[ -9,   6,   6, ...,  12,  -4,  -4],
       [  8,  -2,  14, ..., -15,  13, -10],
       [-10,  -3,   1, ...,  18, -11,  -8],
       ...,
       [  2,  25,  -2, ...,   4,   7,  -8],
       [  4,   2,  -3, ...,  -4,  -2,  20],
       [ 11,   0,   8, ...,  13,  28, -16]])


 ## solid angle(deg=20): 2.943943200718048e-67
Time to measure solid angle : 6.96

vector dim: 256, number of vector: 256
ray=array([[ -1,   5, -10, ...,  -6, -24,  -7],
       [ -2,  11,   1, ...,  -4,   1, -14],
       [ -9,  -2,  -2, ...,   0, -24,  -3],
       ...,
       [  3,   0,   5, ...,   8,   5,   2],
       [  9,  -4,   1, ...,   4, -20,   7],
       [  0, -16,  12, ...,   3,   3,  -3]])


 ## solid angle(deg=20): 2.2303593571364295e-135
Time to measure solid angle : 88.6

vector dim: 512, number of vector: 512
ray=array([[-19,   7,   2, ...,   6, -17,   6],
       [ -6,  -2, -24, ...,   8, -16,  -1],
       [-18,  22,  14, ..., -14,  -1,  -8],
       ...,
       [ -8,  12,  -5, ..., -17,  16, -21],
       [ -5,   0,  -8, ...,   1,   7,  -2],
       [-18,  13,  21, ...,  -3,   7,  17]])


 ## solid angle(deg=20): 0.0
Time to measure solid angle : 1605.83



In [3]:
result = list()
size_list = [2, 4, 8, 16, 32, 64, 128, 256, 512]
cone_list, dual_cone_list, dc_ray_list,  = [], [], []
for s in size_list:
    print(f"vector dim: {s}, number of vector: {s}")
    start = time.time()
    ray = np.round(np.random.normal(size=[s, s]), sf)*10**sf
    ray = np.asarray(ray, dtype=int)
    cone = Cone(ray, normalize=True)
    cone_list.append(cone)

    dual_cone = cone.dual()
    dual_cone_list.append(dual_cone)

    dual_time = time.time()
    print(f"Time to define dual: {round(dual_time - start, 2)}")
    dc_ray = dual_cone.rays()
    dc_ray = dc_ray/np.std(dc_ray)
    dc_ray_r = np.zeros_like(dc_ray)
    for i, ray in enumerate(dc_ray):
        for j, e in enumerate(ray):
            dc_ray_r[i, j] = np.round(float(e), 4)*1e4
    dc_ray_r = np.asarray(dc_ray_r, dtype=int)
    dc_ray_list.append(dc_ray_r)

    # A = matrix(dc_ray_r)
    # dual_ray_time = time.time()
    # # print(f"Time to get dual basis : {round(dual_ray_time - start, 2)}")
    # a = solid_angle_general(A)
    # print(f" ## solid angle: {a}")
    # result.append(a)
    # dc_ray
    # solid_angle_time = time.time()
    # print(f"Time to measure solid angle : {round(solid_angle_time - start, 2)}")
    print()


vector dim: 2, number of vector: 2
Time to define dual: 0.05

vector dim: 4, number of vector: 4
Time to define dual: 0.01

vector dim: 8, number of vector: 8
Time to define dual: 0.03

vector dim: 16, number of vector: 16
Time to define dual: 0.03

vector dim: 32, number of vector: 32
Time to define dual: 0.13

vector dim: 64, number of vector: 64
Time to define dual: 0.75

vector dim: 128, number of vector: 128
Time to define dual: 5.45

vector dim: 256, number of vector: 256
Time to define dual: 89.67


/tmp/ipykernel_475133/3542891929.py:18: RuntimeWarning: divide by zero encountered in divide
  dc_ray = dc_ray/np.std(dc_ray)
/tmp/ipykernel_475133/3542891929.py:18: RuntimeWarning: invalid value encountered in divide
  dc_ray = dc_ray/np.std(dc_ray)


ValueError: cannot convert float NaN to integer

In [3]:
np.where([True, False, True])[0]

array([0, 2])

In [ ]:
target = (dataset.targets.clone().detach().numpy() == cls)
num_candidate = np.where(target == 1)[0]


In [5]:
np.random.choice()

0.5263447341982757

In [21]:
from cl_gym.benchmarks.utils import DEFAULT_DATASET_DIR

import torchvision
mnist_train = torchvision.datasets.MNIST(DEFAULT_DATASET_DIR, train=True, download=True)
target_classes = mnist_train.targets

In [22]:
cls_idx = np.random.choice(mnist_train.targets.unique().cpu().numpy(), size=10,replace=False)

In [23]:
task_id = 2

start_class = (task_id-1) * 2
end_class = task_id * 2
# For CIFAR-like datasets in torchvision where targets are list
# target_classes = dataset.targets.clone().detach().numpy()
selected_indices = np.where(np.logical_and(start_class <= target_classes, target_classes < end_class))[0]


In [28]:
cls_idx

array([6, 8, 3, 1, 4, 5, 9, 7, 2, 0])

In [37]:
c = cls_idx[start_class:end_class]

In [51]:
cls_idx[start_class:end_class]

array([3, 1])

In [42]:
c

1

In [52]:
indices = np.zeros_like(target_classes)
for c in cls_idx[start_class:end_class]:
    indices = np.logical_or(indices, target_classes == c)
selected_indices = np.where(indices)[0]

array([    3,     6,     7, ..., 59984, 59994, 59996])

In [57]:
np.unique(indices[:20].cpu().numpy())

array([0, 1], dtype=uint8)

In [54]:
target_classes[np.where(indices)[0]]

tensor([1, 1, 3,  ..., 1, 1, 3])

In [58]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
a, b, *_ = 1, 2, 3, 4, 5

In [2]:
_

[3, 4, 5]

In [36]:
import torchvision
from cl_gym.benchmarks.utils import DEFAULT_DATASET_DIR
from cl_gym.benchmarks.transforms import get_default_fashion_mnist_transform
import torch

transforms = get_default_fashion_mnist_transform(1)[0]
fashion_mnist_train = torchvision.datasets.FashionMNIST(DEFAULT_DATASET_DIR, train=True, download=True, transform=transforms,)


In [33]:
loader = torch.utils.data.DataLoader(fashion_mnist_train, 32, True)

AttributeError: 'DataLoader' object has no attribute 'to'

In [37]:
y = loader.dataset.targets.cpu().numpy()
y_torch = loader.dataset.targets.to("cuda")

In [53]:
d = dict()
for c in y_torch.unique():
    c = c.cpu().item()
    d[c] = (y_torch==c).nonzero().reshape(-1)

In [56]:
d[0].shape

torch.Size([6000])

In [38]:
y_torch.unique()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device='cuda:0')

In [41]:
(y_torch.unique()==c).nonzero()

tensor([[9]], device='cuda:0')

In [66]:
class A():
    def __init__(self):
        self.a = "a"
    def aa(self):
        def bb():
            return "bb"
        print(bb())
        return "aa"

In [67]:
a = A()
a.aa()

bb


'aa'

In [69]:
new_l0_grads = torch.empty((0, 10), device="cuda", dtype=torch.float32)

In [71]:
new_l0_grads.shape

torch.Size([0, 10])

In [73]:
a = {x:[] for x in range(10)}
a[0].append('a')
a

{0: ['a'], 1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: [], 8: [], 9: []}